# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-03-31 18:06:32
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\users\kalus\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    Landuse = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\SiteSelection.gdb\\Landuse"
    Rivers = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\SiteSelection.gdb\\Rivers"
    Roads = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\SiteSelection.gdb\\Roads"

    # Process: Buffer (Buffer) (analysis)
    Rivers_Buffer = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\Project_5_IndustrialSite\\Project_5_IndustrialSite.gdb\\Rivers_Buffer"
    arcpy.analysis.Buffer(in_features=Rivers, out_feature_class=Rivers_Buffer, buffer_distance_or_field="200 Meters", dissolve_option="ALL")

    # Process: Erase (Erase) (analysis)
    Landuse_NoRivers = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\Project_5_IndustrialSite\\Project_5_IndustrialSite.gdb\\Landuse_NoRivers"
    arcpy.analysis.Erase(in_features=Landuse, erase_features=Rivers_Buffer, out_feature_class=Landuse_NoRivers)

    # Process: Buffer_Roads_500m (Buffer) (analysis)
    Roads_Buffer = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\Project_5_IndustrialSite\\Project_5_IndustrialSite.gdb\\Roads_Buffer"
    arcpy.analysis.Buffer(in_features=Roads, out_feature_class=Roads_Buffer, buffer_distance_or_field="500 Meters", dissolve_option="ALL")

    # Process: Intersect (Intersect) (analysis)
    Landuse_NearRoads = "E:\\vector2\\vector2\\GEOG_424HU_Project_5\\Project_5_IndustrialSite\\Project_5_IndustrialSite.gdb\\Landuse_NearRoads"
    arcpy.analysis.Intersect(in_features=[[Landuse_NoRivers, ""], [Roads_Buffer, ""]], out_feature_class=Landuse_NearRoads)

    # Process: Make Feature Layer (Make Feature Layer) (management)
    Agric_Layer = "Agric_Layer"
    arcpy.management.MakeFeatureLayer(in_features=Landuse_NearRoads, out_layer=Agric_Layer)

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    Agric_Selected, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=Agric_Layer, where_clause="LAND_TYPE = 'Agriculture'")

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
    Agric_with_area = arcpy.management.CalculateGeometryAttributes(in_features=Agric_Selected, geometry_property=[["AREA_M2", "AREA"]], area_unit="SQUARE_METERS", coordinate_system="PROJCS[\"NAD_1983_UTM_Zone_15N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-93.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")[0]

    # Process: Select Layer By Attribute (2) (Select Layer By Attribute) (management)
    Final_Sites, Count_2_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=Agric_with_area, where_clause="AREA_M2 >= 500000")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="E:\\vector2\\vector2\\GEOG_424HU_Project_5\\Project_5_IndustrialSite\\Project_5_IndustrialSite.gdb", workspace="E:\\vector2\\vector2\\GEOG_424HU_Project_5\\Project_5_IndustrialSite\\Project_5_IndustrialSite.gdb"):
        Model()
